version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm build:storybook
            - run: npm deploy:storybook
workflows:
  build-and-test-deploy:
    jobs:
      - build-and-test-deploy
