version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.22.0

commands:
  install_dependencies:
    steps:
      - run: yarn
  set_deploy_key:
    description: Sets the ssh key for project access
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'SHA256:EyQ1Bb6CwFYtyN+KcJsGMsR0T4yip3DHWvrze4p/PDA chenxiaoyao6228@163.com'
jobs:
  test:
    executor: node
    steps: 
      - set_deploy_key
      - checkout
      - install_dependencies
      - run: yarn test 
  build_and_deploy:
    executor: node
    steps:
      - set_deploy_key
      - checkout
      - install_dependencies
      - run: yarn build:storybook
      - run: yarn deploy:storybook 

workflows:
  deploy:
    jobs:
      - test
      - build_and_deploy:
          requires: 
            - test
          filters:
            branches:
              only: master
